import { registerBlock } from '../registry';

registerBlock({
  type: 'CatalogItemBlock',
  name: 'Catalog Item',
  category: 'Ecommerce',
  icon: '🏷️',
  description: 'Individual catalog item with image, name and description. Similar to ProductCardBlock but without cart functionality.',
  fields: {
    CategoryId: { type: 'category-select', title: 'Category', description: 'Filter products by category' },
    ProductId: { type: 'product-select', title: 'Product', placeholder: 'Select a product' },
    Name: { type: 'string', title: 'Name' },
    Sku: { type: 'string', title: 'SKU / Reference', placeholder: 'e.g. SHIRT-001' },
    ShortDescription: { type: 'textarea', title: 'Short Description' },
    LongDescription: { type: 'textarea', title: 'Detailed Description' },
    Image: { type: 'image', title: 'Main Image' },
    Price: { type: 'string', title: 'Price' },
    OriginalPrice: { type: 'string', title: 'Original Price (shown crossed out)', placeholder: 'Leave empty if no discount' },
    CurrencySymbol: { type: 'string', title: 'Currency Symbol', placeholder: '€, $, £', defaultValue: '€' },
    Stock: { type: 'string', title: 'Available Stock' },
    ShowStock: { type: 'bool', title: 'Show Stock on Card', defaultValue: 'false' },
    Category: { type: 'string', title: 'Category', placeholder: 'e.g. Clothing, Electronics' },
    Tags: { type: 'string', title: 'Tags (comma-separated)', placeholder: 'e.g. vegan, sale, new, bestseller' },
    Sizes: { type: 'string', title: 'Sizes (comma-separated)', placeholder: 'e.g. XS,S,M,L,XL' },
    Colors: { type: 'string', title: 'Colors (comma-separated)', placeholder: 'e.g. Red,Blue,Black' },
    CustomOptions: { type: 'string', title: 'Custom Options (comma-separated)', placeholder: 'e.g. Gluten-free, Spicy' },
    Badge: { type: 'string', title: 'Badge Label', placeholder: 'e.g. New, Sale, Bestseller' },
    BadgeColor: { type: 'color', title: 'Badge Color', defaultValue: '#e53e3e' },
    ShowRating: { type: 'bool', title: 'Show Star Rating', defaultValue: 'false' },
    Rating: { type: 'string', title: 'Rating (0-5)', placeholder: 'e.g. 4.5', defaultValue: '5' },
    ReviewCount: { type: 'string', title: 'Review Count', placeholder: 'e.g. 128' },
    BackgroundColor: { type: 'color', title: 'Card Background', defaultValue: '#ffffff' },
    ButtonText: { type: 'string', title: 'Button Text', defaultValue: 'Add to cart' },
    HideButton: { type: 'bool', title: 'Hide Buy Button', defaultValue: 'false' },
  },
});
