import { registerBlock } from '../registry';

registerBlock({
  type: 'ChatBlock',
  name: 'AI Assistant',
  category: 'AI',
  icon: 'fa-robot',
  description: 'Modern AI chatbot. Use Fullscreen for a DeepSeek/Gemini-style full-page chat, or Embedded for a card-style widget.',
  fieldsArray: [
    { name: 'displayMode', type: 'select', title: 'Display Mode', options: [{ label: 'Fullscreen (AI desktop style)', value: 'fullscreen' }, { label: 'Embedded (card widget)', value: 'embedded' }], defaultValue: 'embedded' },
    { name: 'backgroundColor', type: 'color', title: 'Block Background Color', defaultValue: '#FFFFFF' },
    { name: 'borderColor', type: 'color', title: 'Block Border Color', defaultValue: '#E2E8F0' },
    { name: 'borderRadius', type: 'text', title: 'Block Border Radius', placeholder: '16px', defaultValue: '16px' },
    { name: 'title', type: 'text', title: 'Title' },
    { name: 'headerBgColor', type: 'color', title: 'Header Background Color', defaultValue: '#6366F1' },
    { name: 'headerGradientColor', type: 'color', title: 'Header Gradient End Color', defaultValue: '#8B5CF6' },
    { name: 'headerTextColor', type: 'color', title: 'Header Text Color', defaultValue: '#FFFFFF' },
    { name: 'titleSize', type: 'text', title: 'Title Size', placeholder: '18px', defaultValue: '18px' },
    { name: 'logo', type: 'image', title: 'Header Logo' },
    { name: 'logoSize', type: 'text', title: 'Logo Size', placeholder: '28px', defaultValue: '28px' },
    { name: 'aiLogo', type: 'image', title: 'AI Avatar Logo' },
    { name: 'aiLogoSize', type: 'text', title: 'AI Avatar Size', placeholder: '28px', defaultValue: '28px' },
    { name: 'chatBgColor', type: 'color', title: 'Chat Background Color', defaultValue: '#F8FAFC' },
    { name: 'userBubbleColor', type: 'color', title: 'User Message Bubble Color', defaultValue: '#6366F1' },
    { name: 'userTextColor', type: 'color', title: 'User Message Text Color', defaultValue: '#FFFFFF' },
    { name: 'aiBubbleColor', type: 'color', title: 'AI Message Bubble Color', defaultValue: '#FFFFFF' },
    { name: 'aiTextColor', type: 'color', title: 'AI Message Text Color', defaultValue: '#1E293B' },
    { name: 'aiBubbleBorderColor', type: 'color', title: 'AI Bubble Border Color', defaultValue: '#E2E8F0' },
    { name: 'inputBgColor', type: 'color', title: 'Input Background Color', defaultValue: '#FFFFFF' },
    { name: 'inputTextColor', type: 'color', title: 'Input Text Color', defaultValue: '#0F172A' },
    { name: 'inputBorderColor', type: 'color', title: 'Input Border Color', defaultValue: '#CBD5E1' },
    { name: 'inputPlaceholderColor', type: 'color', title: 'Input Placeholder Color', defaultValue: '#94A3B8' },
    { name: 'sendButtonColor', type: 'color', title: 'Send Button Color', defaultValue: '#6366F1' },
    { name: 'aiProvider', type: 'select', title: 'AI Provider', options: [{ label: 'Auto (site default)', value: 'auto' }, { label: 'Ollama (local)', value: 'ollama' }], defaultValue: 'auto' },
    { name: 'customPrompt', type: 'text', title: 'Custom System Prompt (persona only)', placeholder: "Dile a la IA cómo actuar..." },
    { name: 'welcomeMessage', type: 'text', title: 'Welcome Message', placeholder: '¡Hola! ¿En qué puedo ayudarte?' },
  ],
});