import { registerBlock } from '../registry';

registerBlock({
  type: 'FeatureGridBlock',
  name: 'Feature Grid',
  category: 'Content',
  icon: 'fa-th-large',
  description: 'Display a grid of feature cards with icons. Perfect for services, benefits, or platform features sections.',
  fieldsArray: [
    { name: 'title', type: 'text', title: 'Section Title' },
    { name: 'titleColor', type: 'color', title: 'Title Color', defaultValue: '#ffffff' },
    { name: 'titleSize', type: 'text', title: 'Title Size', placeholder: 'E.g.: 2rem or 32px', defaultValue: '2rem' },
    { name: 'subtitle', type: 'text', title: 'Subtitle / Description' },
    { name: 'subtitleColor', type: 'color', title: 'Subtitle Color', defaultValue: '#9ca3af' },
    { name: 'subtitleSize', type: 'text', title: 'Subtitle Size', placeholder: 'E.g.: 1rem', defaultValue: '1rem' },
    { name: 'columns', type: 'text', title: 'Columns', placeholder: 'E.g.: 3', defaultValue: '3' },
    { name: 'gap', type: 'text', title: 'Gap', placeholder: 'E.g.: 1rem or 16px', defaultValue: '1rem' },
    { name: 'backgroundColor', type: 'color', title: 'Background Color' },
    { name: 'paddingY', type: 'text', title: 'Container Padding', placeholder: 'E.g.: 3rem', defaultValue: '3rem' },
    { name: 'maxWidth', type: 'text', title: 'Container Max Width', placeholder: 'E.g.: 1200px', defaultValue: '1200px' },
    { name: 'icon1', type: 'text', title: 'Feature 1 — Icon (FA class)', placeholder: 'E.g.: fas fa-key' },
    { name: 'icon1Color', type: 'color', title: 'Feature 1 — Icon Color', defaultValue: '#5B6EF5' },
    { name: 'title1', type: 'text', title: 'Feature 1 — Title' },
    { name: 'description1', type: 'text', title: 'Feature 1 — Description' },
    { name: 'icon2', type: 'text', title: 'Feature 2 — Icon', placeholder: 'E.g.: fas fa-credit-card' },
    { name: 'icon2Color', type: 'color', title: 'Feature 2 — Icon Color', defaultValue: '#5B6EF5' },
    { name: 'title2', type: 'text', title: 'Feature 2 — Title' },
    { name: 'description2', type: 'text', title: 'Feature 2 — Description' },
    { name: 'icon3', type: 'text', title: 'Feature 3 — Icon', placeholder: 'E.g.: fas fa-building' },
    { name: 'icon3Color', type: 'color', title: 'Feature 3 — Icon Color', defaultValue: '#5B6EF5' },
    { name: 'title3', type: 'text', title: 'Feature 3 — Title' },
    { name: 'description3', type: 'text', title: 'Feature 3 — Description' },
    { name: 'icon4', type: 'text', title: 'Feature 4 — Icon', placeholder: 'E.g.: fas fa-robot' },
    { name: 'icon4Color', type: 'color', title: 'Feature 4 — Icon Color', defaultValue: '#5B6EF5' },
    { name: 'title4', type: 'text', title: 'Feature 4 — Title' },
    { name: 'description4', type: 'text', title: 'Feature 4 — Description' },
    { name: 'icon5', type: 'text', title: 'Feature 5 — Icon', placeholder: 'E.g.: fas fa-paint-brush' },
    { name: 'icon5Color', type: 'color', title: 'Feature 5 — Icon Color', defaultValue: '#5B6EF5' },
    { name: 'title5', type: 'text', title: 'Feature 5 — Title' },
    { name: 'description5', type: 'text', title: 'Feature 5 — Description' },
    { name: 'icon6', type: 'text', title: 'Feature 6 — Icon', placeholder: 'E.g.: fas fa-pen-ruler' },
    { name: 'icon6Color', type: 'color', title: 'Feature 6 — Icon Color', defaultValue: '#5B6EF5' },
    { name: 'title6', type: 'text', title: 'Feature 6 — Title' },
    { name: 'description6', type: 'text', title: 'Feature 6 — Description' },
  ],
});