import { registerBlock } from '../registry';

registerBlock({
  type: 'FlexibleImageTextBlock',
  name: 'Flexible Image + Text',
  category: 'Content',
  icon: '🖼️',
  description: 'Section with image and text side by side. Image can go left or right. Ideal for alternating sections.',
  fields: {
    BackgroundColor: { type: 'color', title: 'Background Color', defaultValue: 'transparent' },
    BackgroundImage: { type: 'image', title: 'Background Image' },
    BackgroundOpacity: { type: 'string', title: 'Background Opacity', placeholder: '0.1 - 1', defaultValue: '1' },
    PaddingVertical: { type: 'string', title: 'Vertical Padding (Tailwind)', placeholder: 'py-8, py-12', defaultValue: 'py-12' },
    PaddingHorizontal: { type: 'string', title: 'Horizontal Padding (Tailwind)', placeholder: 'px-4, px-6', defaultValue: 'px-6' },
    Layout: {
      type: 'select', title: 'Layout',
      options: [
        { value: 'image-left', label: 'Image Left' },
        { value: 'image-right', label: 'Image Right' },
        { value: 'image-top', label: 'Image Top' },
        { value: 'image-bottom', label: 'Image Bottom' },
        { value: 'two-columns', label: 'Two Columns' },
      ],
      defaultValue: 'image-left',
    },
    VerticalAlignment: {
      type: 'select', title: 'Vertical Alignment',
      options: [
        { value: 'start', label: 'Top' },
        { value: 'center', label: 'Center' },
        { value: 'end', label: 'Bottom' },
      ],
      defaultValue: 'center',
    },
    Gap: { type: 'string', title: 'Gap between image and text', placeholder: 'gap-4, gap-6, gap-8', defaultValue: 'gap-8' },
    Title: { type: 'string', title: 'Title' },
    TitleColor: { type: 'color', title: 'Title Color', defaultValue: '#000000' },
    TitleSize: { type: 'string', title: 'Title Size', placeholder: 'text-2xl, text-3xl', defaultValue: 'text-3xl' },
    TitleWeight: {
      type: 'select', title: 'Title Weight',
      options: [
        { value: 'font-normal', label: 'Normal' },
        { value: 'font-medium', label: 'Medium' },
        { value: 'font-semibold', label: 'Semibold' },
        { value: 'font-bold', label: 'Bold' },
      ],
      defaultValue: 'font-bold',
    },
    TitleMarginBottom: { type: 'string', title: 'Title bottom margin', placeholder: 'mb-2, mb-4', defaultValue: 'mb-4' },
    SubTitle: { type: 'string', title: 'Subtitle' },
    SubTitleColor: { type: 'color', title: 'Subtitle Color', defaultValue: '#000000' },
    SubTitleSize: { type: 'string', title: 'Subtitle Size', placeholder: 'text-xl, text-2xl', defaultValue: 'text-xl' },
    SubTitleMarginBottom: { type: 'string', title: 'Subtitle bottom margin', placeholder: 'mb-2, mb-4', defaultValue: 'mb-3' },
    Image: { type: 'image', title: 'Image' },
    ImageWidth: { type: 'string', title: 'Image Width', placeholder: 'w-full, w-1/2', defaultValue: 'w-full' },
    ImageMaxWidth: { type: 'string', title: 'Image Max Width', placeholder: 'max-w-md, max-w-lg', defaultValue: 'max-w-full' },
    ImageBorderRadius: {
      type: 'select', title: 'Image Corners',
      options: [
        { value: 'rounded-none', label: 'None' },
        { value: 'rounded', label: 'Small' },
        { value: 'rounded-lg', label: 'Medium' },
        { value: 'rounded-xl', label: 'Large' },
        { value: 'rounded-full', label: 'Circle' },
      ],
      defaultValue: 'rounded-lg',
    },
    ImageShadow: {
      type: 'select', title: 'Image Shadow',
      options: [
        { value: 'shadow-none', label: 'None' },
        { value: 'shadow-sm', label: 'Small' },
        { value: 'shadow', label: 'Normal' },
        { value: 'shadow-lg', label: 'Large' },
        { value: 'shadow-xl', label: 'Extra large' },
      ],
      defaultValue: 'shadow-lg',
    },
    Text: { type: 'textarea', title: 'Text' },
    TextColor: { type: 'color', title: 'Text Color', defaultValue: '#000000' },
    TextSize: { type: 'string', title: 'Text Size', placeholder: 'text-base, text-lg', defaultValue: 'text-base' },
    ButtonText: { type: 'string', title: 'Button Text' },
    ButtonLink: { type: 'url', title: 'Button Link' },
    ButtonStyle: {
      type: 'select', title: 'Button Style',
      options: [
        { value: 'primary', label: 'Primary' },
        { value: 'secondary', label: 'Secondary' },
        { value: 'outline', label: 'Outline' },
      ],
      defaultValue: 'primary',
    },
  },
});
