import { registerBlock } from '../registry';

registerBlock({
  type: 'FloatingChatBlock',
  name: 'Floating Chat Button',
  category: 'AI',
  icon: 'fa-comment-dots',
  description: 'A modern floating chat button with glassmorphism panel, animated gradients, and fully customizable colors.',
  fieldsArray: [
    { name: 'position', type: 'select', title: 'Position', options: [{ label: 'Right ▶', value: 'right' }, { label: '◀ Left', value: 'left' }], defaultValue: 'right' },
    { name: 'buttonColor', type: 'color', title: 'Button Primary Color', defaultValue: '#6366F1' },
    { name: 'buttonGradientColor', type: 'color', title: 'Button Gradient End Color', defaultValue: '#8B5CF6' },
    { name: 'buttonTextColor', type: 'color', title: 'Button Icon Color', defaultValue: '#FFFFFF' },
    { name: 'buttonIcon', type: 'text', title: 'Button Icon (emoji or text)', placeholder: '💬', defaultValue: '💬' },
    { name: 'buttonSize', type: 'text', title: 'Button Size (px)', placeholder: '60px', defaultValue: '60px' },
    { name: 'buttonGlow', type: 'boolean', title: 'Button Glow Effect', defaultValue: true },
    { name: 'panelBgColor', type: 'color', title: 'Panel Background Color', defaultValue: '#0F172A' },
    { name: 'headerBgColor', type: 'color', title: 'Panel Header Background Start', defaultValue: '#1E293B' },
    { name: 'headerGradientColor', type: 'color', title: 'Panel Header Gradient End', defaultValue: '#6366F1' },
    { name: 'headerTextColor', type: 'color', title: 'Header Text Color', defaultValue: '#F8FAFC' },
    { name: 'chatBgColor', type: 'color', title: 'Chat Background Color', defaultValue: '#0F172A' },
    { name: 'userBubbleColor', type: 'color', title: 'User Message Bubble Color', defaultValue: '#6366F1' },
    { name: 'userTextColor', type: 'color', title: 'User Message Text Color', defaultValue: '#FFFFFF' },
    { name: 'aiBubbleColor', type: 'color', title: 'AI Message Bubble Color', defaultValue: '#1E293B' },
    { name: 'aiTextColor', type: 'color', title: 'AI Message Text Color', defaultValue: '#E2E8F0' },
    { name: 'inputBgColor', type: 'color', title: 'Input Background Color', defaultValue: '#1E293B' },
    { name: 'inputTextColor', type: 'color', title: 'Input Text Color', defaultValue: '#F8FAFC' },
    { name: 'inputBorderColor', type: 'color', title: 'Input Border Color', defaultValue: '#334155' },
    { name: 'sendButtonColor', type: 'color', title: 'Send Button Color', defaultValue: '#6366F1' },
    { name: 'aiProvider', type: 'select', title: 'AI Provider', options: [{ label: 'Auto (site default)', value: 'auto' }, { label: 'Ollama (local)', value: 'ollama' }], defaultValue: 'auto' },
    { name: 'customPrompt', type: 'text', title: 'Custom System Prompt (persona only)', placeholder: 'You are a helpful assistant for this website...' },
    { name: 'welcomeMessage', type: 'text', title: 'Welcome Message', placeholder: 'Hi! How can I help you today?' },
    { name: 'logo', type: 'image', title: 'Chat Logo' },
    { name: 'logoSize', type: 'text', title: 'Logo Size', placeholder: '28px', defaultValue: '28px' },
    { name: 'aiLogo', type: 'image', title: 'AI Avatar Logo' },
    { name: 'aiLogoSize', type: 'text', title: 'AI Avatar Size', placeholder: '28px', defaultValue: '28px' },
  ],
});