import { registerBlock } from '../registry';

registerBlock({
  type: 'FullColumnBlock',
  name: 'Columns',
  category: 'Layout',
  icon: 'fa-columns',
  description: 'Multi-column layout container. Add any blocks inside each column for flexible page layouts.',
  isGroup: true,
  fieldsArray: [
    { name: 'backgroundColor', type: 'color', title: 'Background Color' },
    { name: 'backgroundImage', type: 'image', title: 'Background Image' },
    { name: 'backgroundOverlayOpacity', type: 'text', title: 'Overlay Opacity (0-1)', placeholder: 'e.g., 0.5', defaultValue: '0' },
    { name: 'backgroundOverlayColor', type: 'color', title: 'Overlay Color', defaultValue: '#000000' },
    { name: 'backgroundBlur', type: 'text', title: 'Background Blur (px)', placeholder: '0', defaultValue: '0' },
    { name: 'backgroundBrightness', type: 'text', title: 'Background Brightness', placeholder: '1', defaultValue: '1' },
    { name: 'enableParallax', type: 'boolean', title: 'Enable Parallax', defaultValue: false },
    { name: 'columnLayout', type: 'text', title: 'Column Layout', defaultValue: 'auto' },
    { name: 'maxColumns', type: 'text', title: 'Max Columns (Desktop)', placeholder: '3', defaultValue: '3' },
    { name: 'tabletColumns', type: 'text', title: 'Tablet Columns (md)', placeholder: '2', defaultValue: '2' },
    { name: 'mobileColumns', type: 'text', title: 'Mobile Columns (sm)', placeholder: '1', defaultValue: '1' },
    { name: 'gap', type: 'text', title: 'Gap Between Columns', defaultValue: 'gap-6' },
    { name: 'gapMobile', type: 'text', title: 'Gap Mobile', defaultValue: 'gap-4' },
    { name: 'gapDesktop', type: 'text', title: 'Gap Desktop', defaultValue: 'gap-8' },
    { name: 'paddingY', type: 'text', title: 'Vertical Padding', placeholder: '3rem', defaultValue: '3rem' },
    { name: 'paddingX', type: 'text', title: 'Horizontal Padding', placeholder: '1.5rem', defaultValue: '1.5rem' },
    { name: 'paddingTop', type: 'text', title: 'Padding Top', placeholder: 'e.g., 2rem' },
    { name: 'paddingBottom', type: 'text', title: 'Padding Bottom', placeholder: 'e.g., 2rem' },
    { name: 'marginTop', type: 'text', title: 'Margin Top', placeholder: 'e.g., 2rem' },
    { name: 'marginBottom', type: 'text', title: 'Margin Bottom', placeholder: 'e.g., 2rem' },
    { name: 'itemsAlign', type: 'text', title: 'Items Alignment', defaultValue: 'stretch' },
    { name: 'sectionId', type: 'text', title: 'Section ID (Anchor)', placeholder: 'e.g., services' },
    { name: 'minHeight', type: 'text', title: 'Min Height', defaultValue: 'auto' },
    { name: 'reverseOnMobile', type: 'boolean', title: 'Reverse on Mobile', defaultValue: false },
    { name: 'useContainerQueries', type: 'boolean', title: 'Use Container Queries', defaultValue: false },
    { name: 'borderRadius', type: 'text', title: 'Border Radius', defaultValue: 'rounded-none' },
    { name: 'shadow', type: 'text', title: 'Shadow', defaultValue: 'shadow-none' },
    { name: 'border', type: 'text', title: 'Border', placeholder: 'e.g., 1px solid #e5e7eb' },
    { name: 'zIndex', type: 'text', title: 'Z-Index', defaultValue: 'auto' },
    { name: 'titleSida', type: 'text', title: 'Header (Above Title)' },
    { name: 'titleSidaColor', type: 'color', title: 'Header Color' },
    { name: 'titleSidaSize', type: 'text', title: 'Header Size', placeholder: '1rem' },
    { name: 'titleSidaAlign', type: 'text', title: 'Header Alignment', defaultValue: 'left' },
    { name: 'title', type: 'text', title: 'Main Title' },
    { name: 'titleColor', type: 'color', title: 'Title Color' },
    { name: 'titleSize', type: 'text', title: 'Title Size', placeholder: '2rem' },
    { name: 'titleBorder', type: 'text', title: 'Title Border', placeholder: '1px solid #000' },
    { name: 'titleWeight', type: 'text', title: 'Title Weight', placeholder: 'normal, bold, 400, 600, 700' },
    { name: 'titleAlignment', type: 'text', title: 'Title Alignment', defaultValue: 'left' },
    { name: 'subTitle', type: 'text', title: 'Subtitle' },
    { name: 'subTitleColor', type: 'color', title: 'Subtitle Color' },
    { name: 'subTitleSize', type: 'text', title: 'Subtitle Size', placeholder: '1.1rem' },
    { name: 'subTitleBorder', type: 'text', title: 'Subtitle Border', placeholder: '1px solid #000' },
    { name: 'subTitleWeight', type: 'text', title: 'Subtitle Weight' },
    { name: 'subTitleAlignment', type: 'text', title: 'Subtitle Alignment', defaultValue: 'left' },
    { name: 'text', type: 'text', title: 'Text' },
    { name: 'textColor', type: 'color', title: 'Text Color' },
    { name: 'textSize', type: 'text', title: 'Text Size', placeholder: '1rem' },
    { name: 'textBorder', type: 'text', title: 'Text Border', placeholder: '1px solid #000' },
    { name: 'textWeight', type: 'text', title: 'Text Weight' },
    { name: 'textAlignment', type: 'text', title: 'Text Alignment', defaultValue: 'left' },
    { name: 'description', type: 'richtext', title: 'Description (HTML)' },
    { name: 'descriptionColor', type: 'color', title: 'Description Color' },
    { name: 'descriptionBorder', type: 'text', title: 'Description Border', placeholder: '1px solid #000' },
    { name: 'descriptionWeight', type: 'text', title: 'Description Weight' },
    { name: 'descriptionAlignment', type: 'text', title: 'Description Alignment', defaultValue: 'left' },
    { name: 'headerTextAlign', type: 'text', title: 'Header Text Alignment', defaultValue: 'left' },
    { name: 'hideOnMobile', type: 'boolean', title: 'Hide on Mobile', defaultValue: false },
    { name: 'hideOnTablet', type: 'boolean', title: 'Hide on Tablet', defaultValue: false },
    { name: 'hideOnDesktop', type: 'boolean', title: 'Hide on Desktop', defaultValue: false },
    { name: 'customClasses', type: 'text', title: 'Custom CSS Classes' },
    { name: 'customStyles', type: 'richtext', title: 'Custom Styles', placeholder: 'background: linear-gradient(...);' },
    { name: 'dataAttributes', type: 'richtext', title: 'Data Attributes', placeholder: '{"data-gsap":"fade","data-speed":"1"}' },
    { name: 'stickySection', type: 'boolean', title: 'Sticky Section', defaultValue: false },
    { name: 'stickyTopOffset', type: 'text', title: 'Sticky Top Offset', defaultValue: '0' },
  ],
});