import { registerBlock } from '../registry';

registerBlock({
  type: 'GridColumn',
  name: 'Grid Column',
  category: 'Columns',
  icon: '🔲',
  description: 'Grid with large decorative title in the background. Use children for the elements. Impactful visual effect for feature sections.',
  isGroup: true,
  fields: {
    BackgroundColor: { type: 'color', title: 'Background Color', defaultValue: 'transparent' },
    BackgroundImage: { type: 'image', title: 'Background Image' },
    BackgroundOverlayOpacity: { type: 'string', title: 'Background overlay opacity (0-1)', placeholder: 'e.g. 0.5', defaultValue: '0' },
    BackgroundOverlayColor: { type: 'color', title: 'Background overlay color', defaultValue: '#000000' },
    MaxColumns: { type: 'string', title: 'Max columns (desktop)', placeholder: '1, 2, 3, 4, 5 or 6', defaultValue: '3' },
    TabletColumns: { type: 'string', title: 'Tablet columns (md)', placeholder: '1, 2, 3 or 4 — independent of desktop' },
    Gap: { type: 'string', title: 'Gap between items', placeholder: 'gap-6 or gap-8', defaultValue: 'gap-6' },
    PaddingY: { type: 'string', title: 'Vertical padding', placeholder: 'e.g. 3rem or 48px', defaultValue: '3rem' },
    PaddingX: { type: 'string', title: 'Horizontal padding', placeholder: 'e.g. 1.5rem or 24px', defaultValue: '1.5rem' },
    ItemsAlign: { type: 'select', title: 'Items alignment', options: [{ value: 'start', label: 'Start' }, { value: 'center', label: 'Center' }, { value: 'end', label: 'End' }, { value: 'stretch', label: 'Stretch' }], defaultValue: 'stretch' },
    SectionId: { type: 'string', title: 'Section ID (anchor)', placeholder: 'e.g. servicios (for #servicios)' },
    TitleSida: { type: 'string', title: 'Eyebrow (above title)' },
    TitleSidaColor: { type: 'color', title: 'Eyebrow Color' },
    TitleSidaSize: { type: 'string', title: 'Eyebrow Size', placeholder: 'e.g. 1rem or 16px' },
    TitleSidaAlign: { type: 'select', title: 'Eyebrow Alignment', options: [{ value: 'left', label: 'Left' }, { value: 'center', label: 'Center' }, { value: 'right', label: 'Right' }], defaultValue: 'left' },
    Title: { type: 'string', title: 'Main Title' },
    TitleColor: { type: 'color', title: 'Title Color' },
    TitleSize: { type: 'string', title: 'Title Size', placeholder: 'e.g. 2rem or 32px' },
    SubTitle: { type: 'string', title: 'Subtitle' },
    SubTitleColor: { type: 'color', title: 'Subtitle Color' },
    SubTitleSize: { type: 'string', title: 'Subtitle Size', placeholder: 'e.g. 1.1rem or 18px' },
    Description: { type: 'textarea', title: 'Description (below subtitle)' },
    DescriptionColor: { type: 'color', title: 'Description Color' },
    HeaderTextAlign: { type: 'select', title: 'Header text alignment', options: [{ value: 'left', label: 'Left' }, { value: 'center', label: 'Center' }, { value: 'right', label: 'Right' }], defaultValue: 'left' },
  },
});
