import { registerBlock } from '../registry';

registerBlock({
  type: 'ProductColumnBlock',
  name: 'Product Columns',
  category: 'Ecommerce',
  icon: 'fas fa-th-list',
  description: 'Column layout optimized for product listings. Each column renders a product card with cart support.',
  isGroup: true,
  fields: {
    Title: { type: 'string', title: 'Block Title', placeholder: 'e.g. Our Products' },
    TitleColor: { type: 'color', title: 'Title Color', defaultValue: '#1e293b' },
    TitleSize: { type: 'string', title: 'Title Size', placeholder: '32px', defaultValue: '32px' },
    SubTitle: { type: 'string', title: 'Subtitle' },
    SubTitleColor: { type: 'color', title: 'Subtitle Color' },
    SubTitleSize: { type: 'string', title: 'Subtitle Size', placeholder: 'e.g. 1.1rem or 18px' },
    Description: { type: 'textarea', title: 'Description (below subtitle)' },
    DescriptionColor: { type: 'color', title: 'Description Color' },
    HeaderTextAlign: { type: 'select', title: 'Header Text Alignment', options: [{ value: 'left', label: 'Left' }, { value: 'center', label: 'Center' }, { value: 'right', label: 'Right' }], defaultValue: 'left' },
    HeaderWidth: { type: 'select', title: 'Header Width', options: [{ value: 'narrow', label: 'Narrow' }, { value: 'normal', label: 'Normal' }, { value: 'wide', label: 'Wide' }, { value: 'full', label: 'Full' }], defaultValue: 'normal' },
    AutoMode: { type: 'bool', title: '🛍️ Fetch all products automatically', defaultValue: 'true', description: 'Active: shows all stored products (can filter by category). Inactive: insert child blocks manually.' },
    ShowCategoryFilter: { type: 'bool', title: 'Show category filter (tabs)', defaultValue: 'false', description: 'Shows "All" tabs + each product category above the grid' },
    ShowSidebar: { type: 'bool', title: 'Show Category Sidebar', defaultValue: 'true' },
    Columns: { type: 'string', title: 'Columns (products per row)', placeholder: '4', defaultValue: '4' },
    ProductsPerPage: { type: 'string', title: 'Products Per Page', placeholder: '12', defaultValue: '12' },
    BackgroundColor: { type: 'color', title: 'Background Color', defaultValue: '#f8fafc' },
    CardBgColor: { type: 'color', title: 'Card Background Color', defaultValue: '#ffffff' },
    AccentColor: { type: 'color', title: 'Accent Color (buttons, active state)', defaultValue: '#2563eb' },
    PaddingY: { type: 'string', title: 'Padding Top/Bottom', placeholder: '3rem', defaultValue: '3rem' },
    ShowStock: { type: 'bool', title: 'Show Stock Badge', defaultValue: 'true' },
    ShowRating: { type: 'bool', title: 'Show Rating Stars', defaultValue: 'false' },
    ButtonText: { type: 'string', title: 'Button Text', placeholder: 'Add to cart', defaultValue: 'Add to cart' },
    FilterCategories: { type: 'string', title: 'Filter by Category (comma-separated)', placeholder: 'Manga, Novela, Comics' },
    ForceManual: { type: 'bool', title: 'Force Manual Mode (use as block container only)', defaultValue: 'false' },
    CurrencySymbol: { type: 'string', title: 'Currency Symbol', placeholder: '€, kr, $, £', defaultValue: 'kr' },
    IsRestaurant: { type: 'bool', title: 'Restaurant Mode (food orders)', defaultValue: 'false' },
    RestaurantName: { type: 'string', title: 'Restaurant Name', placeholder: 'e.g. Pizza Place', visibleWhen: 'IsRestaurant:true' },
    OrderButtonText: { type: 'string', title: 'Order Button Text', placeholder: 'Place order', defaultValue: 'Place order', visibleWhen: 'IsRestaurant:true' },
    NtfyTopic: { type: 'string', title: '🔔 Notification channel (ntfy)', placeholder: 'e.g. myrestaurant-orders', description: 'How it works: 1) Download free "ntfy" app on your phone. 2) Subscribe to the channel you enter here. 3) Every time an order comes in, you get a push notification.', visibleWhen: 'IsRestaurant:true' },
  },
});
