import { registerBlock } from '../registry';

registerBlock({
  type: 'ProductCardBlock',
  name: 'Product Card',
  category: 'Ecommerce',
  icon: 'fas fa-box',
  description: 'Product card with image, price, stock and Add to cart button. Connects with the product catalog.',
  isGroup: false,
  fields: {
    ProductId: { type: 'product-select', title: 'Product', placeholder: 'Select a product' },
    Name: { type: 'string', title: 'Product Name' },
    Description: { type: 'textarea', title: 'Short Description', placeholder: 'Product description' },
    LongDescription: { type: 'textarea', title: 'Long Description', placeholder: 'Full product description' },
    Price: { type: 'string', title: 'Price', placeholder: 'Ex: 29.99' },
    OriginalPrice: { type: 'string', title: 'Original Price (before discount)', placeholder: 'Ex: 39.99' },
    CurrencySymbol: { type: 'string', title: 'Currency Symbol', placeholder: '€, kr, $, £', defaultValue: 'kr' },
    Stock: { type: 'string', title: 'Stock', placeholder: 'Ex: 100' },
    Image: { type: 'image', title: 'Main Image' },
    ImagesJson: { type: 'string', title: 'Additional Images (JSON array)', placeholder: '["url1", "url2", ...]' },
    Category: { type: 'string', title: 'Category' },
    Tags: { type: 'string', title: 'Tags (comma-separated)', placeholder: 'tag1, tag2' },
    Sizes: { type: 'string', title: 'Sizes (comma-separated)', placeholder: 'S, M, L, XL' },
    Colors: { type: 'string', title: 'Colors (comma-separated)', placeholder: 'Red, Blue, Green' },
    CustomOptions: { type: 'textarea', title: 'Custom Options (JSON)', placeholder: '{"option1": ["A", "B"], ...}' },
    Badge: { type: 'string', title: 'Badge (e.g. "New", "Sale")' },
    Rating: { type: 'string', title: 'Rating (0-5)', placeholder: '4.5' },
    ReviewCount: { type: 'string', title: 'Review Count', placeholder: '100' },
    Sku: { type: 'string', title: 'SKU', placeholder: 'SKU-001' },
    BackgroundColor: { type: 'color', title: 'Background Color', defaultValue: '#ffffff' },
    ShowStock: { type: 'bool', title: 'Show Stock Badge', defaultValue: 'true' },
    ShowRating: { type: 'bool', title: 'Show Rating Stars', defaultValue: 'false' },
    ButtonText: { type: 'string', title: 'Button text', defaultValue: 'Add to cart' },
    IsRestaurant: { type: 'bool', title: 'Restaurant Mode', defaultValue: 'false' },
  },
});
